### ISSUE TITLE
consider adding DISA STIG

### ISSUE THREAD

**Issue by tdewin** [GustavBrock/Veeam.Linux#3]
https://github.com/VeeamHub/veeam-hardened-repository

**Comment by GustavBrock** [comment]
Sorry, don't know what dsig is.
Have in mind please, that my article series is aimed at those Windows admins who, like me, have minimal or zero knowledge about Linux.

**Comment by tdewin** [comment]
Ok well Veeam has opensourced the following script to harden your ubuntu repository:
https://github.com/VeeamHub/veeam-hardened-repository/blob/master/veeam.harden.sh

It's just a shell script that apply a multitude of security measures

**Comment by GustavBrock** [comment]
Thanks. Before attempting so, I would like it to support the current Ubuntu 22.04.2 LTS.
